# Generated by Django 5.2.1 on 2025-06-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("are_components_ordered", models.BooleanField(default=False)),
                ("are_components_arrived", models.BooleanField(default=False)),
                ("are_components_installed", models.BooleanField(default=False)),
                ("is_pc_build_tested", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("delivered_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Order Progress",
                "verbose_name_plural": "Order Progresses",
                "ordering": ("-completed_on", "-order__created_on"),
            },
        ),
        migrations.CreateModel(
            name="PCBuild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "PC Build",
                "verbose_name_plural": "PC Builds",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PCComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField(default="", null=True)),
            ],
            options={
                "verbose_name": "PC Component",
                "verbose_name_plural": "PC Components",
                "ordering": ("price", "name"),
            },
        ),
        migrations.CreateModel(
            name="PCBuildOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("build", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="builder.pcbuild")),
                (
                    "customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "progress",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="builder.orderprogress"),
                ),
            ],
            options={
                "verbose_name": "PC Build Order",
                "verbose_name_plural": "PC Build Orders",
                "ordering": ("-created_on",),
            },
        ),
        migrations.AddField(
            model_name="orderprogress",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_progress",
                to="builder.pcbuildorder",
            ),
        ),
        migrations.AddField(
            model_name="pcbuild",
            name="components",
            field=models.ManyToManyField(to="builder.pccomponent"),
        ),
    ]
