# Generated by Django 5.2.1 on 2025-06-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcbuild",
            name="price",
        ),
        migrations.RemoveField(
            model_name="pcbuildorder",
            name="progress",
        ),
        migrations.AlterField(
            model_name="orderprogress",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="builder.pcbuildorder",
            ),
        ),
    ]
