# Generated by Django 5.2.1 on 2025-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0002_remove_pcbuild_price_remove_pcbuildorder_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pccomponent",
            name="link",
            field=models.URLField(default=""),
        ),
    ]
