# Generated by Django 5.2.1 on 2025-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0003_alter_pccomponent_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcbuildorder",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
