# Generated by Django 5.2.1 on 2025-06-09 10:59

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_pcbuildorder_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcbuildorder",
            name="markup",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="pcbuildorder",
            name="address",
            field=models.CharField(blank=True, default="The customer didn't provide an address", max_length=100),
        ),
    ]
