# Generated by Django 5.2.17 on 2026-08-08 14:37

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0005_pcbuildorder_markup_alter_pcbuildorder_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcbuildorder",
            name="markup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="pccomponent",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="pcbuildorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("markup__gte", Decimal("0.00"))),
                name="pcbuildorder_markup_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="pccomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", Decimal("0.00"))),
                name="pccomponent_price_non_negative",
            ),
        ),
    ]
