# Generated by Django 5.2.17 on 2026-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_sync_comment_relation_and_drop_like_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
