# Generated by Django 5.2.17 on 2026-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
    ]
