# Generated by Django 5.2.17 on 2026-08-08 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_is_html"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="chatthread",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_thread",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["thread", "timestamp"], name="chat_chatme_thread__a19d84_idx"),
        ),
    ]
